<div class="container">
	<div class="found-box">
		<h6 class="notFound">404</h6>
		<p class="p-found">
			Not found
		</p>
		<img src="public/images/martine_025.jpg" alt="martine 404">
	</div>
	<div class="found-box">
		<p class="return">Retour à la page d'acceuil :</p>
		<a href="index.php?page=home" class="link-backHome">	
			<div class="backHome">
				<p>
					Bordel
					<br>
					Box
				</p>
			</div>
		</a>
	</div>
</div>