<div class="clearfix">
		
	<a href="index.php?page=single&titre=" class="linkh">
	<!-- ajouter id="" dans url-->
		<div class="box-sc">
			<p>
				<i class="fa fa-code icon-cat" aria-hidden="true"></i>
				titre <?= $error ?>
			</p>
		</div>
	</a>

	<a href="#" class="btn-m"><i class="fa fa-wrench icon-ms" aria-hidden="true"></i> Modifier</a></li>
	<a href="#" class="btn-s"><i class="fa fa-trash" aria-hidden="true"></i> Supprimer</a></li>

</div>
