<div class="clearfix">
		
	<a href="index.php?page=single&titre=<?= urlencode($title) ?>" class="linkh">
		<div class="box-sc">
			<p>
				<i class="fa fa-code icon-cat" aria-hidden="true"></i>
				 <?= $title ?>
			</p>
		</div>
	</a>
	
	<a class="btn-m" href="index.php?page=modif&id=<?= $id ?>"><i class="fa fa-wrench icon-ms" aria-hidden="true"></i> Modifier</a>

	<a class="btn-s" href="index.php?page=delete&id=<?= $id ?>"><i class="fa fa-trash" aria-hidden="true"></i> Supprimer</a>
	

</div>
