<div class="clearfix">
		
	<a href="index.php?page=single&titre=<?= urlencode($title) ?>" class="linkh">
		<div class="box-sc">
			<p>
				<i class="fa fa-code icon-cat" aria-hidden="true"></i>
				 <?= $title ?>
				 <?= $error ?>
			</p>
		</div>
	</a>

	<button type="submit" class="btn-m"><i class="fa fa-wrench icon-ms" aria-hidden="true"></i> Modifier</button>
	<button type="submit" class="btn-s"><i class="fa fa-trash" aria-hidden="true"></i> Supprimer</button>

</div>
