<div class="clearfix">	
	<a href="index.php?page=single&lang=<?= htmlentities($lang) ?>&cat=<?= htmlentities($category) ?>&id=<?= htmlentities($id) ?>" class="linkh">
		<div class="box-sc-out">
			<p>
				<i class="fa fa-code icon-cat" aria-hidden="true"></i>
				 <?= htmlentities($title)?>
			</p>
		</div>
	</a>
	<a class="btn-m" href="index.php?page=modif&id=<?= htmlentities($id)?>"><i class="fa fa-wrench icon-ms" aria-hidden="true"></i> Modifier</a>
	<a class="btn-s" href="index.php?page=delete&id=<?= htmlentities($id)?>"><i class="fa fa-trash" aria-hidden="true"></i> Supprimer</a>
</div>
