<div class="clearfix">
		
	<a class="linkh" href="index.php?page=single&titre=<?= urlencode($title) ?>" >
		<div class="box-sc">
			<p>
				<i class="fa fa-code icon-cat" aria-hidden="true"></i>
				 <?= htmlentities($title)?>
			</p>
		</div>
	</a>
	
	<a class="btn-m" href="index.php?page=modif&id=<?= htmlentities($id)?>"><i class="fa fa-wrench icon-ms" aria-hidden="true"></i> Modifier</a>

	<a class="btn-s" href="index.php?page=delete&id=<?= htmlentities($id)?>"><i class="fa fa-trash" aria-hidden="true"></i> Supprimer</a>

</div>
