<header class="header">
	<h1 class="titreHeader clearfix"><a class="link" href="index.php?page=home">B#rdel_<span>Box</span></a></h1>
	<nav class="menu">
		<ul class="clearfix">
			<li class="loginHeader"><a class="new-btn" href="index.php?page=logout">Logout <i class="fa fa-ban" aria-hidden="true"></i></a></li>

			<li class="loginHeader create"><a class="new-btn" href="index.php?page=creation">Create <i class="fa fa-plus-circle" aria-hidden="true"></i></a></li>

			<li class="loginHeader">Connecté en tant que : <?= htmlentities($_SESSION["admin"]) ?></li>
		</ul>
	</nav>
</header>