<div class="container">

	<main>
<div class="container">
			<h2>Nos Cours</h2>
			<a href="#">
				<article class="colonne linkHome">
					<h3>HTML</h3>
					<p>
						 le format de données conçu pour représenter les pages web. C’est un langage de balisage permettant d’écrire de l’hypertexte, d’où son nom. HTML permet également de structurer sémantiquement et de mettre en forme le contenu des pages, d’inclure des ressources multimédias dont des images, des formulaires de saisie, et des programmes informatiques. Il permet de créer des documents interopérables avec des équipements très variés de manière conforme aux exigences de l’accessibilité du web.
					</p>
				</article>
			</a>
			<a href="#">
				<article class="colonne2 linkHome">
					<h3>CSS</h3>
					<p>
						Les feuilles de style en cascade1, généralement appelées CSS de l'anglais Cascading Style Sheets, forment un langage informatique qui décrit la présentation des documents HTML et XML. Les standards définissant CSS sont publiés par le World Wide Web Consortium (W3C). Introduit au milieu des années 1990, CSS devient couramment utilisé dans la conception de sites web et bien pris en charge par les navigateurs web dans les années 2000.
					</p>
				</article>
			</a>
			<div class="clearfix"></div>
			<div class="border"></div>
			<a href="#">
				<article class="colonne linkHome">
					<h3>JavaScript</h3>
					<p>
						JavaScript est un langage de programmation de scripts principalement employé dans les pages web interactives mais aussi pour les serveurs2. C'est un langage orienté objet à prototype, c'est-à-dire que les bases du langage et ses principales interfaces sont fournies par des objets qui ne sont pas des instances de classes, mais qui sont chacun équipés de constructeurs permettant de créer leurs propriétés, et notamment une propriété de prototypage qui permet d'en créer des objets héritiers personnalisés.
					</p>
				</article>
			</a>
			<a href="#">
				<article class="colonne2 linkHome">
					<h3>PHP</h3>
					<p>
						PHP: Hypertext Preprocessor5, plus connu sous son sigle PHP (acronyme récursif), est un langage de programmation libre6, principalement utilisé pour produire des pages Web dynamiques via un serveur HTTP5, mais pouvant également fonctionner comme n'importe quel langage interprété de façon locale. PHP est un langage impératif orienté objet.
						PHP a permis de créer un grand nombre de sites web célèbres, comme Facebook, Wikipédia, etc.7 Il est considéré comme la base de la création des sites Internet dits dynamiques.
					</p>
				</article>
			</a>
		<div class="clearfix"></div>
		<p class="footer">Ceci est un footer</p>
		</div>

	</main>


</div>