<div class="container">

	<main>

		<h2 class="lesson">Nos cours</h2>
		<article class="linkArea">
			<a href="#">
				<h3>HTML</h3>
			</a>
		</article>
		<article class="linkArea">
			<a href="#">
				<h3>CSS</h3>
			</a>
		</article>
		<article class="linkArea">
			<a href="#">
				<h3>PHP</h3>
			</a>
		</article>
		<article class="linkArea">
			<a href="#">
				<h3>JavaScript</h3>
			</a>
		</article>

	</main>


</div>