<div class="container">

	<main>
<div class="container">
			<h2>Nos Cours</h2>
			<a href="#">
				<article class="colonne linkHome">
					<h3>HTML</h3>
					<p>
						 Le format de données conçu pour représenter les pages web. C’est un langage de balisage permettant d’écrire de l’hypertexte, d’où son nom.
					</p>
				</article>
			</a>
			<a href="#">
				<article class="colonne2 linkHome">
					<h3>CSS</h3>
					<p>
						Les feuilles de style en cascade1, généralement appelées CSS de l'anglais Cascading Style Sheets, forment un langage informatique qui décrit la présentation des documents HTML et XML.
					</p>
				</article>
			</a>
			<div class="clearfix"></div>
			<div class="border"></div>
			<a href="#">
				<article class="colonne linkHome">
					<h3>JavaScript</h3>
					<p>
						JavaScript est un langage de programmation de scripts principalement employé dans les pages web interactives mais aussi pour les serveurs.
					</p>
				</article>
			</a>
			<a href="#">
				<article class="colonne2 linkHome">
					<h3>PHP</h3>
					<p>
						PHP: Hypertext Preprocessor5, plus connu sous son sigle PHP (acronyme récursif), est un langage de programmation libre.
					</p>
				</article>
			</a>
		<div class="clearfix"></div>
		<p class="footer">Ceci est un footer</p>
		</div>

	</main>


</div>