<div class="container">
	<h2>HTML</h2>
	<div class="border-h"></div>
	<h3 class="sous-cat">Introduction</h3>
	<a href="#" class="linkh">
		<div class="box-sc">
			<p>
				<i class="fa fa-code icon-cat" aria-hidden="true"></i>
				Ceci est le premier cours.
			</p>
		</div>
	</a>
	<a href="#" class="linkh">
	<div class="box-sc">
		<p>
			<i class="fa fa-code icon-cat" aria-hidden="true"></i>
			Ceci est le deuxième cours.
		</p>
	</div>
	</a>
	<div class="border-h"></div>
	<h3 class="sous-cat">Suite</h3>
	<a href="#" class="linkh">
		<div class="box-sc">
			<p>
				<i class="fa fa-code icon-cat" aria-hidden="true"></i>
				Encore un cours.
			</p>
		</div>
	</a>
	<a href="#" class="linkh">
	<div class="box-sc">
		<p>
			<i class="fa fa-code icon-cat" aria-hidden="true"></i>
			Wa mais c'est un cours.
		</p>
	</div>
	</a>
</div>