<!-- <h2>Connexion :</h2>
<form method="POST">

	<div><?= $error ?></div>

	<label for="name">Identifiant Administrateur :</label>
	<input type="text" name="name" id="name">

	<label for="pwd">Mot de passe Administrateur :</label>
	<input type="password" name="pwd" id="pwd">

	<button type="submit">Connexion</button>
	
</form> -->

<div id="login-form">

    <h3>Login</h3>

    <fieldset>

      <form action="javascript:void(0);" method="get">

        <input type="email" required value="Email" onBlur="if(this.value=='')this.value='Email'" onFocus="if(this.value=='Email')this.value='' "> <!-- JS because of IE support; better: placeholder="Email" -->

        <input type="password" required value="Password" onBlur="if(this.value=='')this.value='Password'" onFocus="if(this.value=='Password')this.value='' "> <!-- JS because of IE support; better: placeholder="Password" -->

        <input type="submit" value="Entrer">

        <footer class="clearfix">

        </footer>

      </form>

    </fieldset>

  </div> <!-- end login-form -->
