<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>tinymce.init({ selector:'textarea' });</script>
<div class="container">
    <h2>Modif</h2>
    <form method="post" align="center" class="clearfix">

    	<div><?= $error ?></div>

    	<input type="hidden" value="<?= $id ?>" >
		
		<label class="creation customLabel" for="titre">Titre :</label>
        <input class="creation customInput" type="text" name="titre" placeholder="Titre du cours" id="titre" value="<?= $titre ?>" required="required" />
		
		<label class="creation customLabel" for="objectif">Objectif du cours :</label>
        <input class="creation customInput" type="textarea" name="objectif" value="<?= $objectif ?>" placeholder="Votre objectif içi" id="objectif" required="required"/>

        <textarea class="moduleCreation" name="textBox"><?= $contenu ?></textarea>

        <button type="submit" class="publish btn btn-primary btn-block btn-large cre">Publier</button>

    </form>
</div>
