<h2>Inscription</h2>
    <form method="post" align="center" class="clearfix">

        <input class="creation customInput" type="text" name="pseudo" placeholder="Votre pseudo"  value="" required="required" />

        <input class="creation customInput" type="email" name="email" placeholder="Votre email"  value="" required="required" />
        
        <h2> </h2>
        <label class="creation customLabel" for="password">Mot de passe : </label>
        <input class="creation customInput" type="password" name="password" placeholder="Votre password"  value="" required="required" />
        
        <input class="creation customInput" type="password2" name="password2" placeholder="Votre password2"  value="" required="required" />        

        <button type="submit" name="register" class="customButton btn cre">Publier</button>

    </form>