<div class="container">


	<h2><?= $titre ?></h2>



	<div class="objectifs">
		<h3>Les objectifs de ce cours :</h3>
		<p><?= $objectif ?></p>
	</div>

	<div class="border-single"></div>

	<div class="contenu">
		<p><?= $contenu ?></p>
	</div>

	<p class="p-date">Date création : <?= $d_creation ?> // Date dernière modif : <?= $d_modif ?></p>

	<a class="btn-in" href="index.php?page=modif&id=<?= $id ?>"><i class="fa fa-wrench icon-ms" aria-hidden="true"></i>Modifier</a>

	<a class="btn-in" href="index.php?page=delete&id=<?= $id ?>"><i class="fa fa-trash" aria-hidden="true"></i> Supprimer</a>
</div>