<h2><?= $single["title"] ?></h2>
<div class="objectifs">
	<h3>Les objectifs de ce cours :</h3>
	<p><?= htmlentities($single["goal"]) ?></p>
</div>
<div class="border-single"></div>
<div class="contenu">
	<p><?= $single["content"] ?></p>
</div>
<p class="p-date">Date création : <?= htmlentities($single["date"]) ?> // Date dernière modif : <?= htmlentities($single["date_last"]); ?></p>
<textarea class="txt-area" placeholder="Laches un comms"></textarea>
<button type="submit" class="new-btn btnComm">Envoyer</button>