<h2><?= $single["title"] ?></h2>
<div class="objectifs">
	<h3>Les objectifs de ce cours :</h3>
	<p><?= htmlentities($single["goal"]) ?></p>
</div>
<div class="border-single"></div>
<div class="contenu">
	<p><?= $single["content"] ?></p>
</div>
<p class="p-date">Date création : <?= htmlentities($single["date"]) ?> // Date dernière modif : <?= htmlentities($single["date_last"]); ?></p>

<form method="POST" class="">
	<div><?= htmlspecialchars($error) ?></div>
	<input name="idLesson" type="text" value="htmlentities($idPage)">
	<input name="author" type="text" placeholder="Pseudo" >
	<textarea name="content" placeholder="Commentaire"></textarea>
	<button type="submit" class="new-btn btnComm">Envoyer</button>
</form>