<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title><?php echo $page ?></title>
	<link href="https://fonts.googleapis.com/css?family=Poiret+One|Yanone+Kaffeesatz" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="public/styles/reset.css">
	<link rel="stylesheet" type="text/css" href="public/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="public/styles/style.css">
</head>
<body>

<?php
require("controllers/header.php");

require("controllers/content.php");

require("controllers/footer.php");
?>

</body>
</html>