<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Bordel_Box</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link href="https://fonts.googleapis.com/css?family=Poiret+One|Yanone+Kaffeesatz" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="public/styles/reset.css">
	<link rel="stylesheet" type="text/css" href="public/font-awesome/css/font-awesome.min.css">
	
	<link rel="stylesheet" type="text/css" href="public/styles/prettify.min.css">
	<link rel="stylesheet" type="text/css" href="public/styles/sons-of-obsidian.css">
	<link rel="stylesheet" type="text/css" href="public/styles/style.css">
</head>
<body>
	<?php
		require("controllers/header.php");

		require("controllers/content.php");

		require("controllers/footer.php");
	?>
	<script src="public/scripts/jquery.min.js"></script>
	<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
	<script src="public/scripts/prettify.min.js"></script>
	<script src="public/scripts/app.js"></script>
</body>
</html>

